import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import java.awt.event.*;
import java.util.Random;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * welcome.java
 *
 * Created on May 5, 2017, 10:39:07 PM
 */

/**
 *
 * @author hp
 */
public class welcome extends javax.swing.JFrame {

    /** Creates new form welcome */
    public welcome() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton29 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jLabel71 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel20 = new javax.swing.JLabel();
        Signup = new javax.swing.JFrame();
        jLabel74 = new javax.swing.JLabel();
        jButton31 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton30 = new javax.swing.JButton();
        jLabel82 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel81 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton5 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jOptionPane1 = new javax.swing.JOptionPane();
        admins = new javax.swing.JFrame();
        jButton22 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jPasswordField4 = new javax.swing.JPasswordField();
        jButton8 = new javax.swing.JButton();
        jLabel69 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        aboutus = new javax.swing.JFrame();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jLabel66 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        gameselection = new javax.swing.JFrame();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        clashroyale = new javax.swing.JFrame();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        forgot = new javax.swing.JFrame();
        jButton13 = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        maintainence = new javax.swing.JFrame();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel52 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Contact = new javax.swing.JFrame();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        adminlog = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        Login.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Login.setMinimumSize(new java.awt.Dimension(1024, 768));
        Login.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                LoginWindowActivated(evt);
            }
        });
        Login.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dont have an account? ");
        Login.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 640, 390, 50));

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("Berlin Sans FB", 1, 36));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Sign Up");
        jButton4.setToolTipText("Create a new account");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Login.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 640, 170, 50));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email Id:-");
        Login.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, -1, -1));

        jButton29.setIcon(new javax.swing.ImageIcon("G:\\edit\\fghjfhjfhjfj.png")); // NOI18N
        jButton29.setBorderPainted(false);
        jButton29.setContentAreaFilled(false);
        jButton29.setFocusable(false);
        Login.getContentPane().add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 40, 40));

        jButton28.setIcon(new javax.swing.ImageIcon("G:\\edit\\jfghjfjf.png")); // NOI18N
        jButton28.setBorderPainted(false);
        jButton28.setContentAreaFilled(false);
        jButton28.setFocusable(false);
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        Login.getContentPane().add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 40));

        jLabel71.setIcon(new javax.swing.ImageIcon("G:\\edit\\bvbvbv.jpg")); // NOI18N
        Login.getContentPane().add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, -1, 60));

        jLabel41.setBackground(new java.awt.Color(0, 0, 0));
        jLabel41.setOpaque(true);
        Login.getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 80));

        jLabel70.setBackground(new java.awt.Color(255, 255, 255));
        jLabel70.setOpaque(true);
        Login.getContentPane().add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1020, 10));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 21));
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("someone123@gmail.com");
        jTextField1.setToolTipText("Enter username");
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 3, true));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        Login.getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 290, 40));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password:-");
        Login.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 255));
        jButton3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Log In");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Login.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, 480, 50));

        jLabel21.setIcon(new javax.swing.ImageIcon("G:\\edit\\ghgh.png")); // NOI18N
        Login.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 190, 190));

        jLabel23.setIcon(new javax.swing.ImageIcon("G:\\edit\\hkhjk.png")); // NOI18N
        Login.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 480, 410));

        jLabel22.setIcon(new javax.swing.ImageIcon("G:\\edit\\ba.png")); // NOI18N
        Login.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 480, 410));

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 20));
        jPasswordField1.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField1.setText("sdsdsdsdsdsdsdsd");
        jPasswordField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 3, true));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
        });
        Login.getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, 290, 40));

        jLabel20.setIcon(new javax.swing.ImageIcon("G:\\edit\\aasasa.jpg")); // NOI18N
        Login.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 770));

        Signup.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Signup.setMinimumSize(new java.awt.Dimension(1024, 768));
        Signup.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                SignupWindowActivated(evt);
            }
        });
        Signup.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel74.setIcon(new javax.swing.ImageIcon("G:\\edit\\bvbvbv.jpg")); // NOI18N
        Signup.getContentPane().add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, -1, 60));

        jButton31.setIcon(new javax.swing.ImageIcon("G:\\edit\\jfghjfjf.png")); // NOI18N
        jButton31.setBorderPainted(false);
        jButton31.setContentAreaFilled(false);
        jButton31.setFocusable(false);
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        Signup.getContentPane().add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 40));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email ID:-");
        Signup.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, 33));

        jButton30.setIcon(new javax.swing.ImageIcon("G:\\edit\\fghjfhjfhjfj.png")); // NOI18N
        jButton30.setBorderPainted(false);
        jButton30.setContentAreaFilled(false);
        jButton30.setFocusable(false);
        Signup.getContentPane().add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 40, 40));

        jLabel82.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 48));
        jLabel82.setForeground(new java.awt.Color(255, 255, 255));
        jLabel82.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel82.setText("Sign Up");
        Signup.getContentPane().add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 170, 80));

        jLabel77.setFont(new java.awt.Font("Century Gothic", 1, 24));
        jLabel77.setForeground(new java.awt.Color(255, 255, 255));
        jLabel77.setText("Username:-");
        Signup.getContentPane().add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, 33));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 20));
        jTextField3.setForeground(new java.awt.Color(153, 153, 153));
        jTextField3.setText(" someone@gmail.com");
        jTextField3.setToolTipText("Should be a valid email");
        jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
        });
        Signup.getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 300, 40));

        jLabel81.setFont(new java.awt.Font("Century Gothic", 1, 24));
        jLabel81.setForeground(new java.awt.Color(255, 255, 255));
        jLabel81.setText("Confirm Password:-");
        Signup.getContentPane().add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, -1, 33));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 20));
        jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2.setText(" Anything");
        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
        });
        Signup.getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 300, 40));

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 20));
        jTextField4.setForeground(new java.awt.Color(153, 153, 153));
        jTextField4.setText("#232323");
        jTextField4.setToolTipText("Must contain '#' with 6 random digits ");
        jTextField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField4FocusGained(evt);
            }
        });
        Signup.getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 300, 40));

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 20));
        jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        jTextField5.setText(" 9425156365");
        jTextField5.setToolTipText("Should be a 10 digit number");
        jTextField5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField5FocusGained(evt);
            }
        });
        Signup.getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 300, 40));

        jPasswordField2.setFont(new java.awt.Font("Tahoma", 0, 20));
        jPasswordField2.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField2.setText("  aaaaaaaaaaaaaaa");
        jPasswordField2.setToolTipText("Must be between 8-50");
        jPasswordField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPasswordField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusGained(evt);
            }
        });
        Signup.getContentPane().add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 300, 40));

        jPasswordField3.setFont(new java.awt.Font("Tahoma", 0, 20));
        jPasswordField3.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField3.setText("aaaaaaaaaaaaaa");
        jPasswordField3.setToolTipText("Should be same as password");
        jPasswordField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPasswordField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField3ActionPerformed(evt);
            }
        });
        jPasswordField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField3FocusGained(evt);
            }
        });
        Signup.getContentPane().add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 540, 220, 40));

        jCheckBox1.setFont(new java.awt.Font("Century Gothic", 1, 18));
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("I agree to terms and conditions");
        jCheckBox1.setContentAreaFilled(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        Signup.getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 600, 357, -1));

        jButton5.setBackground(new java.awt.Color(255, 0, 0));
        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 24));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon("G:\\edit\\rrrrrr.png")); // NOI18N
        jButton5.setText("Sign Up");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setDisabledIcon(new javax.swing.ImageIcon("G:\\edit\\wwww.png")); // NOI18N
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Signup.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 630, -1, -1));

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 20));
        jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        jTextField7.setText("1,2,3");
        jTextField7.setToolTipText("Must contain '#' with 6 random digits ");
        jTextField7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField7FocusGained(evt);
            }
        });
        Signup.getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 300, 40));

        jLabel83.setIcon(new javax.swing.ImageIcon("G:\\edit\\FDSFSDF.png")); // NOI18N
        Signup.getContentPane().add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 70, -1));

        jLabel84.setIcon(new javax.swing.ImageIcon("G:\\edit\\FDSFSDF.png")); // NOI18N
        Signup.getContentPane().add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 70, -1));

        jLabel85.setFont(new java.awt.Font("Century Gothic", 1, 24));
        jLabel85.setForeground(new java.awt.Color(255, 255, 255));
        jLabel85.setText("Player Level:-");
        Signup.getContentPane().add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, 33));

        jLabel7.setForeground(new java.awt.Color(0, 255, 51));
        Signup.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 580, 200, 20));

        jLabel78.setFont(new java.awt.Font("Century Gothic", 1, 24));
        jLabel78.setForeground(new java.awt.Color(255, 255, 255));
        jLabel78.setText("Password:-");
        Signup.getContentPane().add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, -1, 33));

        jLabel79.setFont(new java.awt.Font("Century Gothic", 1, 24));
        jLabel79.setForeground(new java.awt.Color(255, 255, 255));
        jLabel79.setText("Phone No:-");
        Signup.getContentPane().add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, -1, 33));

        jLabel80.setFont(new java.awt.Font("Century Gothic", 1, 24));
        jLabel80.setForeground(new java.awt.Color(255, 255, 255));
        jLabel80.setText("Player Tag:-");
        Signup.getContentPane().add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, 33));

        jLabel76.setIcon(new javax.swing.ImageIcon("G:\\edit\\ghgfhghgfhfgh.png")); // NOI18N
        Signup.getContentPane().add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 500, 620));

        jLabel72.setBackground(new java.awt.Color(0, 0, 0));
        jLabel72.setOpaque(true);
        Signup.getContentPane().add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 80));

        jLabel73.setBackground(new java.awt.Color(255, 255, 255));
        jLabel73.setOpaque(true);
        Signup.getContentPane().add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1020, 10));

        jLabel75.setIcon(new javax.swing.ImageIcon("G:\\edit\\dfsdgsfgdfgfdg.jpg")); // NOI18N
        Signup.getContentPane().add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 770));

        admins.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        admins.setMinimumSize(new java.awt.Dimension(1024, 778));
        admins.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                adminsWindowActivated(evt);
            }
        });
        admins.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton22.setIcon(new javax.swing.ImageIcon("G:\\edit\\jfghjfjf.png")); // NOI18N
        jButton22.setBorderPainted(false);
        jButton22.setContentAreaFilled(false);
        jButton22.setFocusable(false);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        admins.getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 60));

        jButton12.setIcon(new javax.swing.ImageIcon("G:\\edit\\bvbvbv.jpg")); // NOI18N
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.setFocusable(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        admins.getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 80, 80));

        jButton23.setIcon(new javax.swing.ImageIcon("G:\\edit\\fghjfhjfhjfj.png")); // NOI18N
        jButton23.setBorderPainted(false);
        jButton23.setContentAreaFilled(false);
        jButton23.setFocusable(false);
        admins.getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 40, 60));

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 30));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Unique Id :-");
        admins.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel14.setForeground(new java.awt.Color(0, 255, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Your session expires in 60");
        admins.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 310, 90));

        jButton6.setBackground(new java.awt.Color(255, 0, 0));
        jButton6.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Forgot Password??");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton6.setBorderPainted(false);
        jButton6.setFocusable(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        admins.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 670, 510, 40));

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 21));
        jTextField6.setText("someone123@gmail.com");
        jTextField6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 3, true));
        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField6FocusGained(evt);
            }
        });
        admins.getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 510, 330, 40));

        jPasswordField4.setFont(new java.awt.Font("Tahoma", 0, 20));
        jPasswordField4.setText("aaaaaaaaaaaaaa");
        jPasswordField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 3));
        jPasswordField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField4FocusGained(evt);
            }
        });
        admins.getContentPane().add(jPasswordField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, 330, 40));

        jButton8.setBackground(new java.awt.Color(0, 51, 255));
        jButton8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Open");
        jButton8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton8.setBorderPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        admins.getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 620, 510, 40));

        jLabel69.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 30));
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("Password :-");
        admins.getContentPane().add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, -1, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon("G:\\edit\\reddy.png")); // NOI18N
        admins.getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 320, 440));

        jLabel37.setIcon(new javax.swing.ImageIcon("G:\\edit\\princy.png")); // NOI18N
        admins.getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 340, 440));

        jLabel43.setBackground(new java.awt.Color(255, 255, 255));
        jLabel43.setOpaque(true);
        admins.getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1030, 10));

        jLabel40.setBackground(new java.awt.Color(0, 0, 0));
        jLabel40.setOpaque(true);
        admins.getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 80));

        jLabel39.setIcon(new javax.swing.ImageIcon("G:\\edit\\profilr.png")); // NOI18N
        admins.getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, 190));

        jLabel36.setIcon(new javax.swing.ImageIcon("G:\\edit\\ijp;ioj;;joi.jpg")); // NOI18N
        admins.getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 760));

        aboutus.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        aboutus.setMinimumSize(new java.awt.Dimension(1024, 768));
        aboutus.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton26.setIcon(new javax.swing.ImageIcon("G:\\edit\\fghjfhjfhjfj.png")); // NOI18N
        jButton26.setBorderPainted(false);
        jButton26.setContentAreaFilled(false);
        jButton26.setFocusable(false);
        aboutus.getContentPane().add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 40, 40));

        jButton27.setIcon(new javax.swing.ImageIcon("G:\\edit\\jfghjfjf.png")); // NOI18N
        jButton27.setBorderPainted(false);
        jButton27.setContentAreaFilled(false);
        jButton27.setFocusable(false);
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        aboutus.getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 40));

        jLabel66.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36));
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("Class:- XII A");
        aboutus.getContentPane().add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, 210, 50));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon("G:\\edit\\abo.png")); // NOI18N
        aboutus.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1020, 260));

        jLabel68.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36));
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("Name:- Ashwani & Shaurya");
        aboutus.getContentPane().add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 450, 50));

        jLabel67.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 70));
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("\"                                                   \"");
        aboutus.getContentPane().add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 980, 180));

        jLabel65.setIcon(new javax.swing.ImageIcon("G:\\edit\\bvbvbv.jpg")); // NOI18N
        aboutus.getContentPane().add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, -1, 60));

        jLabel64.setBackground(new java.awt.Color(255, 255, 255));
        jLabel64.setOpaque(true);
        aboutus.getContentPane().add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1020, 10));

        jLabel63.setBackground(new java.awt.Color(0, 0, 0));
        jLabel63.setOpaque(true);
        aboutus.getContentPane().add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 80));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setIcon(new javax.swing.ImageIcon("G:\\edit\\fgfdgfdg.jpg")); // NOI18N
        aboutus.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 780));

        gameselection.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        gameselection.setMinimumSize(new java.awt.Dimension(1024, 768));
        gameselection.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                gameselectionWindowActivated(evt);
            }
        });
        gameselection.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton20.setIcon(new javax.swing.ImageIcon("G:\\edit\\jfghjfjf.png")); // NOI18N
        jButton20.setBorderPainted(false);
        jButton20.setContentAreaFilled(false);
        jButton20.setFocusable(false);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        gameselection.getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 40));

        jButton21.setIcon(new javax.swing.ImageIcon("G:\\edit\\fghjfhjfhjfj.png")); // NOI18N
        jButton21.setBorderPainted(false);
        jButton21.setContentAreaFilled(false);
        jButton21.setFocusable(false);
        gameselection.getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 40, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 66)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameselection.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 100, 90));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon("G:\\edit\\dfsdfsdfsdfs.png")); // NOI18N
        gameselection.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 440, 150));

        jLabel29.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 58)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameselection.getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 680, 80));

        jButton7.setBackground(new java.awt.Color(255, 0, 0));
        jButton7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Log  Out");
        jButton7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton7.setBorderPainted(false);
        jButton7.setFocusable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        gameselection.getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 110, 100, 40));

        jButton32.setIcon(new javax.swing.ImageIcon("G:\\edit\\bvbvbv.jpg")); // NOI18N
        jButton32.setBorderPainted(false);
        jButton32.setContentAreaFilled(false);
        jButton32.setFocusable(false);
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        gameselection.getContentPane().add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 80, 80));

        jLabel25.setBackground(new java.awt.Color(0, 0, 0));
        jLabel25.setOpaque(true);
        gameselection.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 80));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setOpaque(true);
        gameselection.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1020, 10));

        jButton14.setIcon(new javax.swing.ImageIcon("G:\\edit\\baaaa.png")); // NOI18N
        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jButton14.setFocusable(false);
        gameselection.getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, 180, 170));

        jButton15.setIcon(new javax.swing.ImageIcon("G:\\edit\\roy.png")); // NOI18N
        jButton15.setBorder(null);
        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.setFocusable(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        gameselection.getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 170, 170));

        jButton16.setIcon(new javax.swing.ImageIcon("G:\\edit\\booo.png")); // NOI18N
        jButton16.setBorderPainted(false);
        jButton16.setContentAreaFilled(false);
        jButton16.setFocusable(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        gameselection.getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 170, 170));

        jLabel30.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 60));
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Welcome Chief,");
        gameselection.getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 680, 80));

        jButton17.setIcon(new javax.swing.ImageIcon("G:\\edit\\hAAA.png")); // NOI18N
        jButton17.setBorderPainted(false);
        jButton17.setContentAreaFilled(false);
        jButton17.setFocusable(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        gameselection.getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 180, 170));

        jLabel24.setIcon(new javax.swing.ImageIcon("G:\\edit\\thgfghgfh.jpg")); // NOI18N
        gameselection.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon("G:\\edit\\CVCXVX.png")); // NOI18N

        jLabel32.setIcon(new javax.swing.ImageIcon("G:\\edit\\FDSFSDF.png")); // NOI18N

        jLabel35.setIcon(new javax.swing.ImageIcon("G:\\edit\\DSGDSGSDGS.png")); // NOI18N

        jLabel34.setIcon(new javax.swing.ImageIcon("G:\\edit\\DFDSGDGFXB.png")); // NOI18N

        jLabel33.setIcon(new javax.swing.ImageIcon("G:\\edit\\JHJHJ.png")); // NOI18N

        javax.swing.GroupLayout clashroyaleLayout = new javax.swing.GroupLayout(clashroyale.getContentPane());
        clashroyale.getContentPane().setLayout(clashroyaleLayout);
        clashroyaleLayout.setHorizontalGroup(
            clashroyaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clashroyaleLayout.createSequentialGroup()
                .addGroup(clashroyaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clashroyaleLayout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(jLabel33)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel31)
                        .addGap(101, 101, 101)
                        .addComponent(jLabel35))
                    .addGroup(clashroyaleLayout.createSequentialGroup()
                        .addGap(381, 381, 381)
                        .addComponent(jLabel34)
                        .addGap(201, 201, 201)
                        .addComponent(jLabel32)))
                .addContainerGap(325, Short.MAX_VALUE))
        );
        clashroyaleLayout.setVerticalGroup(
            clashroyaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clashroyaleLayout.createSequentialGroup()
                .addGroup(clashroyaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clashroyaleLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel35)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel32))
                    .addGroup(clashroyaleLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(clashroyaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addGroup(clashroyaleLayout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(74, 74, 74)
                                .addComponent(jLabel34)))))
                .addContainerGap(195, Short.MAX_VALUE))
        );

        forgot.setMinimumSize(new java.awt.Dimension(1024, 768));
        forgot.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton13.setBackground(new java.awt.Color(255, 0, 0));
        jButton13.setFont(new java.awt.Font("Arial Black", 1, 40));
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("X");
        jButton13.setToolTipText("Close");
        jButton13.setBorder(null);
        jButton13.setBorderPainted(false);
        jButton13.setFocusable(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        forgot.getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 60, 60));

        jLabel48.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48));
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("You are Fired!!!!!!!!!");
        forgot.getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 640, 430, 50));

        jButton10.setIcon(new javax.swing.ImageIcon("G:\\edit\\dc543ae1efee7bf7b1ab144eaacbed2b.png")); // NOI18N
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        forgot.getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 440, -1));

        jLabel49.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 44));
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("How you can be so careless???");
        forgot.getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 590, 60));

        jLabel47.setBackground(new java.awt.Color(255, 255, 255));
        jLabel47.setIcon(new javax.swing.ImageIcon("G:\\edit\\bvbvbv.jpg")); // NOI18N
        jLabel47.setFocusable(false);
        forgot.getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 60));

        jLabel46.setBackground(new java.awt.Color(255, 255, 255));
        jLabel46.setFocusable(false);
        jLabel46.setOpaque(true);
        forgot.getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1030, 10));

        jLabel45.setBackground(new java.awt.Color(0, 0, 0));
        jLabel45.setFocusable(false);
        jLabel45.setOpaque(true);
        forgot.getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 80));

        jLabel44.setIcon(new javax.swing.ImageIcon("G:\\edit\\8uyyuyu.jpg")); // NOI18N
        forgot.getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        maintainence.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        maintainence.setBackground(new java.awt.Color(0, 51, 102));
        maintainence.setMinimumSize(new java.awt.Dimension(1024, 768));
        maintainence.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton18.setIcon(new javax.swing.ImageIcon("G:\\edit\\fghjfhjfhjfj.png")); // NOI18N
        jButton18.setBorderPainted(false);
        jButton18.setContentAreaFilled(false);
        jButton18.setFocusable(false);
        maintainence.getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 40, 40));

        jButton19.setIcon(new javax.swing.ImageIcon("G:\\edit\\jfghjfjf.png")); // NOI18N
        jButton19.setBorderPainted(false);
        jButton19.setContentAreaFilled(false);
        jButton19.setFocusable(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        maintainence.getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 40));

        jLabel52.setIcon(new javax.swing.ImageIcon("G:\\edit\\bvbvbv.jpg")); // NOI18N
        maintainence.getContentPane().add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 70, 80));

        jLabel50.setBackground(new java.awt.Color(255, 255, 255));
        jLabel50.setOpaque(true);
        maintainence.getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1030, 10));

        jLabel51.setBackground(new java.awt.Color(0, 0, 0));
        jLabel51.setOpaque(true);
        maintainence.getContentPane().add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 80));

        jLabel53.setIcon(new javax.swing.ImageIcon("G:\\edit\\zzzzzzzzzzzzz.jpg")); // NOI18N
        maintainence.getContentPane().add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 600, 610));

        jLabel28.setBackground(new java.awt.Color(51, 0, 51));
        jLabel28.setOpaque(true);
        maintainence.getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1030, 780));

        Contact.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Contact.setMinimumSize(new java.awt.Dimension(1024, 768));
        Contact.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton24.setIcon(new javax.swing.ImageIcon("G:\\edit\\fghjfhjfhjfj.png")); // NOI18N
        jButton24.setBorderPainted(false);
        jButton24.setContentAreaFilled(false);
        jButton24.setFocusable(false);
        Contact.getContentPane().add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 40, 40));

        jButton25.setIcon(new javax.swing.ImageIcon("G:\\edit\\jfghjfjf.png")); // NOI18N
        jButton25.setBorderPainted(false);
        jButton25.setContentAreaFilled(false);
        jButton25.setFocusable(false);
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        Contact.getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 40));

        jLabel54.setBackground(new java.awt.Color(255, 255, 255));
        jLabel54.setOpaque(true);
        Contact.getContentPane().add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1020, 10));

        jLabel55.setIcon(new javax.swing.ImageIcon("G:\\edit\\bvbvbv.jpg")); // NOI18N
        Contact.getContentPane().add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, -1, 60));

        jLabel42.setBackground(new java.awt.Color(0, 0, 0));
        jLabel42.setOpaque(true);
        Contact.getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 80));

        jLabel57.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36));
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("Finland.");
        Contact.getContentPane().add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 310, 40));

        jLabel58.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36));
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("+91 9422818996");
        Contact.getContentPane().add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 470, 40));

        jLabel17.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36));
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Address :-       Fan Area, Supercell Headquater, ");
        Contact.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 800, 70));

        jLabel62.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36));
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("supercellfanbase@gmail.com");
        Contact.getContentPane().add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 470, 40));

        jLabel61.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36));
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("Street 44, Helinski,");
        Contact.getContentPane().add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 310, 40));

        jLabel60.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36));
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setIcon(new javax.swing.ImageIcon("G:\\edit\\dggdgdg.png")); // NOI18N
        jLabel60.setText(":-");
        Contact.getContentPane().add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 120, 80));

        jLabel59.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36));
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setIcon(new javax.swing.ImageIcon("G:\\edit\\rgfg.png")); // NOI18N
        jLabel59.setText(":-");
        Contact.getContentPane().add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 110, 80));

        jLabel56.setBackground(new java.awt.Color(0, 0, 0));
        jLabel56.setIcon(new javax.swing.ImageIcon("G:\\edit\\gdfgdfdghd.jpg")); // NOI18N
        Contact.getContentPane().add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 770));

        javax.swing.GroupLayout adminlogLayout = new javax.swing.GroupLayout(adminlog.getContentPane());
        adminlog.getContentPane().setLayout(adminlogLayout);
        adminlogLayout.setHorizontalGroup(
            adminlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        adminlogLayout.setVerticalGroup(
            adminlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Old English Text MT", 1, 56));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome to Supercell");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 580, 90));

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Old English Text MT", 1, 36));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Admin");
        jButton1.setToolTipText("Go to developer login page");
        jButton1.setBorderPainted(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 650, 350, 50));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Old English Text MT", 1, 36));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Player");
        jButton2.setToolTipText("Go to member login page");
        jButton2.setBorderPainted(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 590, 350, 50));

        jLabel18.setIcon(new javax.swing.ImageIcon("G:\\edit\\ki.png")); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 310, 420));

        jLabel19.setIcon(new javax.swing.ImageIcon("G:\\edit\\peke.png")); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 300, 420));

        jLabel1.setIcon(new javax.swing.ImageIcon("G:\\Ash img\\welcome.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        admins.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

     String tf=new String(jPasswordField1.getPassword());




          {
            try
              {
        Class.forName("java.sql.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost/supercell","root","tiger");
                stmt=con.createStatement();
                String query="select * from registered where emailID ='"+jTextField1.getText()+"';";

        System.out.print(query);
rs=stmt.executeQuery(query);
if(rs.next())
{
    String pass=rs.getString("Password");
    if(tf.equals(pass))
    {
        jOptionPane1.showMessageDialog(null,"Login Successful");
        gameselection.setVisible(true);
      
        Login.setVisible(false);
    

    }
    else
        jOptionPane1.showMessageDialog(null,"Incorrect Email ID or Password");
}


            }
        catch(Exception e)
        {
            e.printStackTrace();
                jOptionPane1.showMessageDialog(null,"Error");
        }
        }



    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Signup.setVisible(true);
        Login.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed
Connection con=null;
Statement stmt=null;    
ResultSet rs=null;
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String aa=new String(jPasswordField3.getPassword());
        int ans=jOptionPane1.showConfirmDialog(null,"Do you want to Sign Up");
        if(ans==jOptionPane1.YES_OPTION)
        {
            try
            {
                Class.forName("java.sql.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost/supercell","root","tiger");
                stmt=con.createStatement();
                String query="insert into registered values('"+jTextField2.getText()+"','"+jTextField3.getText()+"','"+jTextField4.getText()+"','"+jTextField5.getText()+"','"+aa+"','"+jTextField7.getText()+"');";
                System.out.print(query);
                stmt.executeUpdate(query);
                jOptionPane1.showMessageDialog(null,"Sign Up successfull");
                Login.setVisible(true);
                Signup.setVisible(false);
            }
            catch(Exception e)
            {
                e.printStackTrace();
                jOptionPane1.showMessageDialog(null,"Error In Sign Up");
            }}
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jPasswordField2.setText("");
        jPasswordField3.setText("");

            

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
       String pd=new String(jPasswordField2.getPassword());
        String cpd=new String(jPasswordField3.getPassword());


          if((jCheckBox1.isSelected()==true) && pd.equals(cpd))
          {
            jButton5.setEnabled(true);
                 jLabel7.setText("Password Matched!!!!");
          }
          else
          {
              if(jCheckBox1.isSelected()==false)
                 jLabel7.setText("Password do not Match!!!");
                  jButton5.setEnabled(false);
          }

        




    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        admins.setVisible(false);
        forgot.setVisible(true);
      
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void gameselectionWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_gameselectionWindowActivated

         String tf=new String(jPasswordField1.getPassword());




          {
            try
              {
        Class.forName("java.sql.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost/supercell","root","tiger");
                stmt=con.createStatement();
                String query="select * from registered where EmailID ='"+jTextField1.getText()+"';";

        System.out.print(query);
rs=stmt.executeQuery(query);
if(rs.next())
{
    String pass=rs.getString("Username");
    String ply=rs.getString("PlayerLvl");
    jLabel29.setText(pass);
    jLabel9.setText(ply);
    Timer ttt=new Timer(800,new ActionListener()
{final Random r=new Random();
    public void actionPerformed(ActionEvent e)
    {
int R = (int)(Math.random()*256);
int G = (int)(Math.random()*256);
int B= (int)(Math.random()*256);
Color color = new Color(R, G, B); //random color, but can be bright or dull

//to get rainbow, pastel colors
Random random = new Random();
final float hue = random.nextFloat();
final float saturation = 1.0f;//1.0 for brilliant, 0.0 for dull
final float luminance = 1.0f; //1.0 for brighter, 0.0 for black
color = Color.getHSBColor(hue, saturation, luminance);

                jLabel29.setForeground(color);

            
    }

});
ttt.start();
} }

        catch(Exception e)
        {
            e.printStackTrace();
                jOptionPane1.showMessageDialog(null,"Error");
        }
        }





    }//GEN-LAST:event_gameselectionWindowActivated

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        gameselection.setVisible(false);
        Login.setVisible(true);
        jTextField1.setText("");
        jPasswordField1.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         String tf=new String(jPasswordField4.getPassword());




          {
            try
              {
        Class.forName("java.sql.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost/supercell","root","tiger");
                stmt=con.createStatement();
                String query="select * from admins where emailID ='"+jTextField6.getText()+"';";

        System.out.print(query);
rs=stmt.executeQuery(query);
if(rs.next())
{
    String pass=rs.getString("Password");
    if(tf.equals(pass))
    {
        jOptionPane1.showMessageDialog(null,"Welcome Boss");
        adminlog.setVisible(true);


    }
    else
        jOptionPane1.showMessageDialog(null,"Boss, something is wrong with you");
}


            }
        catch(Exception e)
        {
            e.printStackTrace();
                jOptionPane1.showMessageDialog(null,"Error");
        }
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        maintainence.setVisible(true);
        gameselection.setVisible(false);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
         maintainence.setVisible(true);
        gameselection.setVisible(false);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        gameselection.setVisible(true);
        maintainence.setVisible(false);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        Login.setVisible(true);
        gameselection.setVisible(false);
        jTextField1.setText("");
        jPasswordField1.setText("");
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    Timer t=new Timer(1000,new ActionListener()
        {
          int a=60;
            public void actionPerformed(ActionEvent e)
            {
                a--;
              
                jLabel14.setText("Your session expires in "+a);
                 if(a==0
                 ){
                     jLabel14.setForeground(Color.red);
                   jLabel14.setText("Your session Expired!!");

                jTextField6.setEnabled(false);
                 jTextField6.setText("");
                jButton8.setEnabled(false);
                jPasswordField4.setEnabled(false);
                jPasswordField4.setText("");
                 jButton6.setEnabled(false);
                 a=60;
                t.stop();
                 }}
             });
    private void adminsWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_adminsWindowActivated
        // TODO add your handling code here:
        
        t.start();
        jLabel39.setFocusable(true);
       
                

    }//GEN-LAST:event_adminsWindowActivated

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        jLabel14.setForeground(Color.green);
        jLabel14.setText("Your session expires in 60");
        admins.setVisible(false);
        t.restart();
        admins.setVisible(true);
        jButton6.setEnabled(true);
         jButton8.setEnabled(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTextField6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusGained
        // TODO add your handling code here:
        jTextField6.setText("");
}//GEN-LAST:event_jTextField6FocusGained

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField1.setForeground(Color.black);
    }//GEN-LAST:event_jTextField1FocusGained

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        // TODO add your handling code here:
        jPasswordField1.setText("");
         jPasswordField1.setForeground(Color.black);
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField4FocusGained
        // TODO add your handling code here:
        jPasswordField4.setText("");
    }//GEN-LAST:event_jPasswordField4FocusGained

    private void LoginWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_LoginWindowActivated
        // TODO add your handling code here:
     jLabel21.setFocusable(true);
    }//GEN-LAST:event_LoginWindowActivated

    private void SignupWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_SignupWindowActivated
        // TODO add your handling code here:

     

        jButton5.setEnabled(false);
          jLabel82.setFocusable(true);
    }//GEN-LAST:event_SignupWindowActivated

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jPasswordField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        // TODO add your handling code here:
        jTextField2.setText("");
        jTextField2.setForeground(Color.black);
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
        // TODO add your handling code here:
          jTextField3.setText("");
        jTextField3.setForeground(Color.black);
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusGained
        // TODO add your handling code here:
          jTextField4.setText("");
        jTextField4.setForeground(Color.black);
    }//GEN-LAST:event_jTextField4FocusGained

    private void jTextField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusGained
        // TODO add your handling code here:
          jTextField5.setText("");
        jTextField5.setForeground(Color.black);
    }//GEN-LAST:event_jTextField5FocusGained

    private void jPasswordField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2FocusGained
        // TODO add your handling code here:
          jPasswordField2.setText("");
        jPasswordField2.setForeground(Color.black);
    }//GEN-LAST:event_jPasswordField2FocusGained

    private void jPasswordField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField3FocusGained
        // TODO add your handling code here:
         jPasswordField3.setText("");
        jPasswordField3.setForeground(Color.black);
    }//GEN-LAST:event_jPasswordField3FocusGained

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        clashroyale.setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jTextField7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusGained
        // TODO add your handling code here:
        jTextField7.setText("");
        jTextField7.setForeground(Color.black);

    }//GEN-LAST:event_jTextField7FocusGained

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Contact;
    private javax.swing.JFrame Login;
    private javax.swing.JFrame Signup;
    private javax.swing.JFrame aboutus;
    private javax.swing.JFrame adminlog;
    private javax.swing.JFrame admins;
    private javax.swing.JFrame clashroyale;
    private javax.swing.JFrame forgot;
    private javax.swing.JFrame gameselection;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JFrame maintainence;
    // End of variables declaration//GEN-END:variables

}
